metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true
- module: elasticsearch
  xpack.enabled: true
  #metricsets:
  #  - node
  #  - node_stats
  period: 10s
  hosts: ["http://es_master_01:9200", "http://es_master_02:9200", "http://es_master_03:9200", "http://es_data_01:9200", "http://es_data_02:9200",  "http://es_data_03:9200",  "http://es_coordinating_node_01:9200"] 
  username: "elastic"
  password: "8E78NY1mnfGvQJ6e7aHy"
- module: kibana
  xpack.enabled: true
  period: 10s
  hosts: ["http://es_cluster_kibana_1:5601"]

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
