metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: elasticsearch
  xpack.enabled: true
  #metricsets:
  #  - node
  #  - node_stats
  period: 10s
  hosts:
    - "http://es01:9120"
    - "http://es02:9120"
    - "http://es03:9120"
    - "http://es01:9200"
    - "http://es02:9200"
    - "http://es03:9200"
  username: "elastic"
  password: "8E78NY1mnfGvQJ6e7aHy"
- module: kibana
  xpack.enabled: true
  period: 10s
  hosts: ["http://vm-cluster-kibana-1:5601"]

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
